# Generated by Django 4.0.4 on 2022-06-01 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coupon',
            options={'verbose_name': 'Скидка', 'verbose_name_plural': 'Скидки'},
        ),
    ]
