# Generated by Django 4.0.4 on 2022-06-03 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_coupon_alter_order_discount_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-created',), 'permissions': (('can_set_status', 'Возможность настройки статуса'),), 'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('NEW', 'Новый заказ'), ('APR', 'Подтверждён'), ('PAY', 'Оплачен'), ('CNL', 'Отменён')], default='NEW', max_length=3, verbose_name='Статус'),
        ),
    ]
